### ISSUE TITLE
Remove references to CWL

### ISSUE THREAD

**Issue by dsikes** [madpipes/cli#1]
there are several hard coded references to 'CWL' within the source code of the project. 

For example:
``` yaml
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
```
cwlVersion should just be 'version'
